language:
  node_js

node_js:
  - "7"

sudo:
  required

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  directories:
    - $HOME/.yarn-cache

install:
  - .travis/setup.sh

script:
  - .travis/ci.sh
  - .travis/coverage.sh

after_success:
  - .travis/build.sh
  - .travis/push.sh